### ISSUE TITLE
Allow to add shapes as part of input molecules

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock-runner#131]
### Please describe the feature you'd like

It would be nice to be able to add shapes are one of the inputs in the haddock runner

### Why is it relevant?

Benchmark of the protein-ligand-shape docking experiments

### Additional context (if any)

Must make sure the input molecules are placed in a given order, maybe: receptor, ligand, shape

**Comment by rvhonorato** [comment]
could you please provide some input data @VGPReys ?

should this feature also be implemented for 2+ @amjjbonvin ?

**Comment by amjjbonvin** [comment]
We have shape support in both 2+ and 3

**Comment by VGPReys** [comment]
https://github.com/haddocking/haddock3/tree/main/examples/docking-protein-ligand-shape
- https://github.com/haddocking/haddock3/blob/main/examples/docking-protein-ligand-shape/data/shape.pdb
- https://github.com/haddocking/haddock3/blob/main/examples/docking-protein-ligand-shape/data/shape-restraints-from-shape-1.tbl
- https://github.com/haddocking/haddock3/blob/main/examples/docking-protein-ligand-shape/data/3DV1-fit-prot.pdb
- https://github.com/haddocking/haddock3/blob/main/examples/docking-protein-ligand-shape/data/ligand-ensemble.pdb

**Comment by rvhonorato** [comment]
> We have shape support in both 2+ and 3

I know, should this feature also be implemented for 2+ @amjjbonvin ?
