### ISSUE TITLE
Implement option to stop and resume the benchmarking

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock-runner#5]

**Comment by VGPReys** [comment]
Resuming would be nice.
I just encountered an issue running  a benchchmark that stopped at `Starting goroutine 279 of 1150`.

I would suggest to either report in a separated files runs that failed and keep going with the other runs,
Or having a solution to restart it form the one that stopped.

**Comment by rvhonorato** [comment]
I've been thinking about this and it's indeed a desired feature but there are a few issues that can arise;

1. The benchmark run should only be resumable if the following do not change:
    - `configuration.yaml` and the`executable` and the `input_list` files
2. How to get the status of a run
3. The actual resume mechanism

For (1) it's possible to create a checksum of the 3 key files and check if they have changed or not. Getting the status (2) would be more complicated because haddock does not have the correct exit codes; see [here](https://github.com/haddocking/haddock3/blob/8e2dff139ef0ed0a5d92a6c85e29af0741c96a83/src/haddock/clis/cli.py#L78C7-L78C7) that the main function does not return any exit codes. The most "straighforward" way would be to parse and interpret the log files to extract the state. Finally for the actual resume mechanism (3), since for some reason haddock3 support restarting, it could be sophisticated and return from the last completed step - but this would also involve something similar to (2) to parse the log and identify _where_ it failed. A simpler approach would be to just remove the whole directory and re-do the execution.

**Comment by rvhonorato** [comment]
[Done in v1.7.0](https://github.com/haddocking/haddock-runner/releases/tag/v1.7.0 )
