### ISSUE TITLE
Identify the run state

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock-runner#88]
It should be possible to parse the `log_{timestamp}.txt` file and assign a state to a run

**Comment by VGPReys** [comment]
For now, I do stdout redirection to a `bechmark.out` followed by `tail -f bechmark.out`.
Using this method, I can already follow the goroutines statments `I1006 22:48:28.870685   37764 main.go:184]  Starting goroutine 164 of 176`.
There is also logs when it failed (`F0924 03:10:12.816045   45065 main.go:200] Failed to run HADDOCK: Error running HADDOCK:`) or was sucessful (`I1006 23:32:10.815861   37764 main.go:211] All jobs completed successfully`).

**Comment by rvhonorato** [comment]
not sure what you mean - what I meant is a way to get the state of a run based on the `log_{timestamp}` file
